[[bond]]
source = "tpknam1qpk6vl0yll8xfshacgvsv8vegzr8jegkmuaz2g0cvsnupgdvxht4u30e92g"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "49530"

[bond.signatures]
tpknam1qpk6vl0yll8xfshacgvsv8vegzr8jegkmuaz2g0cvsnupgdvxht4u30e92g = "signam1qqs7a2xw649z9qzh6lq2h9txvdmq8xahdz7a868cw70nae0avnpfzwkkf9gmaffsfvvly235j8hvz9xvdmmxhwk4p3rn5tmff3js44c0unt9ut"
