[[bond]]
source = "tpknam1qppw7wpk0meraug84rv5lf3gmetcafz8009gdq7qlyh2ee87sjsw76228mq"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "24900"

[bond.signatures]
tpknam1qppw7wpk0meraug84rv5lf3gmetcafz8009gdq7qlyh2ee87sjsw76228mq = "signam1qzna2ed8ztcwkp2vdzzaq60naa7mh6gy9sy02p4d6r6c3g6rlkjsw42ywcfmvjrhsk02fvjs34w0wapp7ugldygez0negpjs9k5kp7sps94zel"
